themes_index = {
    "i feel numb": {"source": "personal_responses", "key": "feel_numb"},
    "i always relapse": {"source": "personal_responses", "key": "failure_and_resilience"},
    "i can't sleep": {"source": "personal_responses", "key": "sleep_trouble"},
    "i'm afraid to quit": {"source": "personal_responses", "key": "fear_to_quit"},
    "i hate myself for using": {"source": "personal_responses", "key": "shame_addiction"},
    "cravings at night": {"source": "personal_responses", "key": "cravings_night"},
    "cravings after work": {"source": "personal_responses", "key": "cravings_stress"},
    "panic attacks": {"source": "personal_responses", "key": "panic_support"},
    "i feel alone": {"source": "personal_responses", "key": "loneliness"},
    "i'm ashamed to tell someone": {"source": "personal_responses", "key": "ashamed_to_talk"},
    "i used to be strong": {"source": "kratom_book", "key": "identity_loss"},
    "nothing feels fun": {"source": "kratom_book", "key": "dopamine_flatline"},
    "what if i fail again": {"source": "kratom_book", "key": "fear_of_failure"},
    "this is the only thing that helps": {"source": "personal_responses", "key": "false_comfort"},
    "i don't know who i am without it": {"source": "personal_responses", "key": "identity_crisis"},
    "i feel like a failure": {"source": "personal_responses", "key": "self_judgment"},
    "i’m scared there's no point": {"source": "personal_responses", "key": "hopelessness"},
    "i'm scared to detox": {"source": "personal_responses", "key": "detox_fear"},
    "i feel like i’ll never be normal": {"source": "personal_responses", "key": "future_normalcy"},
    "i just want to feel better": {"source": "personal_responses", "key": "need_relief"},
    "i want to taper": {"source": "personal_responses", "key": "tapering_request"},
    "i can't tell my partner": {"source": "personal_responses", "key": "partner_secrecy"},
    "i want to give up": {"source": "personal_responses", "key": "despair"},
    "i'm worried i'll lose my job": {"source": "personal_responses", "key": "job_fear"},
    "my stomach hurts": {"source": "personal_responses", "key": "withdrawal_gut"},
    "i keep sweating": {"source": "personal_responses", "key": "sweating_detox"},
    "my body aches": {"source": "personal_responses", "key": "body_pain"},
    "i don’t feel like myself": {"source": "personal_responses", "key": "disconnected_self"},
    "i don’t know where to start": {"source": "personal_responses", "key": "starting_help"},
    "i’m afraid of the future": {"source": "personal_responses", "key": "future_fear"},
    "i'm worried i'll fail again": {"source": "kratom_book", "key": "fear_of_failure"},
    "i feel like a zombie": {"source": "kratom_book", "key": "emotional_numbness"},
    "i miss my old self": {"source": "personal_responses", "key": "lost_identity"},
    "i can't focus": {"source": "personal_responses", "key": "concentration"},
    "i feel brain fog": {"source": "personal_responses", "key": "mental_clarity"},
    "i don't trust myself": {"source": "kratom_book", "key": "self_doubt"},
    "i can’t get through the day": {"source": "personal_responses", "key": "day_to_day_support"},
    "i feel hopeless": {"source": "personal_responses", "key": "encouragement"},
    "i don’t have support": {"source": "personal_responses", "key": "building_support"},
    "low energy": {"source": "personal_responses", "key": "energy_help"},
    "i want to believe this will work": {"source": "testimonials", "key": "early_wins"},
    "i’ve tried everything": {"source": "personal_responses", "key": "rebuild_confidence"},
    "i'm scared of withdrawal": {"source": "personal_responses", "key": "withdrawal_reframe"},
    "i want a plan": {"source": "personal_responses", "key": "structured_path"},
    "i can't afford to relapse": {"source": "kratom_book", "key": "stakes"},
    "i feel shame": {"source": "personal_responses", "key": "compassion_reframe"},
    "i don’t think i can do this": {"source": "kratom_book", "key": "belief_in_self"},
    "i need help tapering": {"source": "personal_responses", "key": "tapering_tips"},
    "i need something to change": {"source": "kratom_book", "key": "breakthrough_call"},
    "i don't feel motivated": {"source": "kratom_book", "key": "motivation_reboot"}
}